dict = {}
m = input("Enter friends name")
n = input("Enter your fav language")
dict.update({m:n})
m = input("Enter friends name")
n = input("Enter your fav language")
dict.update({m:n})
m = input("Enter friends name")
n = input("Enter your fav language")
dict.update({m:n})
m = input("Enter friends name")
n = input("Enter your fav language")
dict.update({m:n})
print(dict)